# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CI-CD

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        permissions:
            contents: read 

        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '22'
            
            - name: Instal WebDriver manager
              run: npm i --save-dev webdriver-manager 
              
            - name: Install Protractor
              run: npm i -g protractor && webdriver-manager update

            - name: Install dependencies
              run: npm ci

            - name: Install Chrome
              run: sudo apt-get install -y google-chrome-stable  

            - name: Install Chrome dependencies
              run: npm i --save-dev install-chrome-dependencies  
            
            - name: Install Eslint
              run: npm i eslint
            
            - name: Lint
              run: npm run lint
        
            - name: Unit test
              run: npm run test:ci
            
            - name: Cleanup old artifacts
              run: rm -rf release.zip
            
            - name: Building app
              run: npm run build -- --configuration=production
            
            - name: Zip artifact for deployment
              run: zip release.zip ./* -r

            - name: Verifying generated files
              run: ls -lah release.zip
              
            - name: Upload artifact for deployment
              uses: actions/upload-artifact@v4
              with:
                name: MyApp-v1
                path: release.zip
    
    Deployment:
        runs-on: ubuntu-latest
        needs: Build
        permissions:
            contents: read
            id-token: write
        env:
            name: "Production"
            URL: myapp-v1-bjdfhkaefcasgcch.swedencentral-01.azurewebsites.net

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: MyApp-v1
            
            - name: Verifying donwload
              run: ls -lah 
              working-directory:
            
            - name: Unzip artifact for deployment
              run: unzip release.zip

            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                enable-AzPSSession: true
            
            - name: Azure CLI script
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                  az account show

#            - name: Check artifact size
#             run: du -sh release.zip
            
#            - name: Check for symlinks
#              run: find release.zip -type l
              
#            - name: Remove symlinks
#              run: find release.zip -type l -delete
            
#            - name: Verify build output
#              run: ls -l release.zip

#            - name: Fix file permissions
#              run: chmod -R 755 release.zip

            - name: 'Deploy to Azure Web App'
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                app-name: 'MyApp-v1'
                slot-name: 'Production'
                package: .