name: CI-CD

on:
    push:
        branches:
            - main

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '22'
            
            - name: Instal WebDriver manager
              run: npm i --save-dev webdriver-manager 
              
            - name: Install Protractor
              run: npm i -g protractor && webdriver-manager update

            - name: Install dependencies
              run: npm ci

            - name: Install Chrome
              run: sudo apt-get install -y google-chrome-stable  

            - name: Install Chrome dependencies
              run: npm i --save-dev install-chrome-dependencies  
            
            - name: Install Eslint
              run: npm i eslint
            
            - name: Lint
              run: npm run lint
        
            - name: Unit test
              run: npm run test:ci
            
            - name: Cleanup old artifacts
              run: rm -rf dist/mon-projet
            
            - name: Building app
              run: npm run build -- --configuration=production
            
            - name: Verifying generated files
              run: ls -lah dist/mon-projet
              
            - name: Upload artifact for GitHub Pages
              uses: actions/upload-artifact@v4
              with:
                name: github-pages
                path: dist/mon-projet
            
            - name: List generated files
              run: ls -la dist/mon-projet
    
    Deployment:
        runs-on: ubuntu-latest
        needs: Build
        permissions:
            pages: write
            id-token: write
        env:
            name: github-pages
            USERS: ${{ github.actor }}
            USERS_ID: ${{ github.actor_id }}
            URL: ${{ github.server_url }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Cleaning old builds
              run: rm -rf dist/mon-projet
            
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: github-pages
                path: dist/mon-projet
            
            - name: Verifying donwload
              run: ls -lah dist/mon-projet
            
            - name: Check artifact size
              run: du -sh dist/mon-projet
            
            - name: Check for symlinks
              run: find dist/mon-projet -type l
              
            - name: Remove symlinks
              run: find dist/mon-projet -type l -delete
            
            - name: Verify build output
              run: ls -l dist/mon-projet

            - name: Fix file permissions
              run: chmod -R 755 dist/mon-projet

            - name: Deploy to GitHub Pages
              id: deployment  
              uses: actions/deploy-pages@v4
              with:
                  artifact_name: github-pages